-- Übersetze einen einen Teil von der Quest Kopfgeld auf die Flusspfotengnolle
UPDATE `quest_template` SET `Title`='Kopfgeld auf die Flusspfotengnolle', `Details`='Gnolle, brutale Wesen, die in dieser Gegend nichts zu suchen haben, sind entlang der Grenzen des Waldes von Elwynn gesehen worden. Ein großes Rudel, viel zu viele, als dass wir allein mit ihnen fertig werden könnten, hat sich in den Wäldern südlich von jenem Wachturm dort eingenistet. Eine weitere Gruppe hat sich im Gebiet nahe des Steinhügelsees im Osten eingenistet. $B$BDie Armee von Sturmwind wird jeden belobigen, der dabei hilft, die Gnolle zu töten. Bringt mir ihre bemalten Gnollarmbinden als Beweis für Eure Tat.', `Objectives`='Bringt Stellvertreter Rainer in der Kaserne 8 bemalte Gnollarmbinden. ' WHERE  `entry`=11 LIMIT 1;
-- Übersetze Ursangus' Tatze
UPDATE `quest_template` SET `Title`='Ursangus\' Tatze', `Details`='Der mächtige Bär Ursangus ist nicht mehr!$b$bDas kleine halbmondförmige Emblem auf seiner Tatze bedeutet, dass das Tier von den Nachtelfen dazu abgerichtet wurde, den Wald zu durchstreifen und nach ihren Feinden zu durchsuchen. Niemand kann sagen, wie viele Eurer Hordebrüder und -schwestern diesem Geschöpf zum Opfer gefallen sind.$B$BIhr solltet die Tatze zu Tarkan in die Silberwindzuflucht bringen. Er wird sich freuen, zu erfahren, dass eine solche Waffe aus dem Arsenal des Feindes entfernt worden ist. ', `Objectives`='Bringt Ursangus\' Tatze zu Hauptmann Tarkan in der Silberwindzuflucht. ', `OfferRewardText`='Ah, die Tatze von Ursangus!$B$BHabt Ihr überhaupt eine Vorstellung davon, wie viel Ärger uns dieses Biest über die Jahre bereitet hat? Diese Zeiten sind nun Dank Euch vorbei.$B$BIch werde diese Trophäe zusammen mit eurem Bericht über den Tod der Beste nach Orgrimmar schicken, damit sie öffentlich ausgestellt werden kann.$B$BMeinen Glückwunsch! ', `RequestItemsText`='Was ist, $R?' WHERE  `entry`=23 LIMIT 1;
-- Übersetze Schattumbras Kopf
UPDATE `quest_template` SET `Title`='Schattumbras Kopf', `Details`='Der einstmals so flinke Schattumbra liegt jetzt regungslos vor Euch und der Sieg ist Euer.$b$bDieses legendäre Geschöpf wird von den Nachtelfen verehrt. Sein Kopf dürfte eine beeindruckende Trophäe sein und als Zeichen für das Ende der Allianz im Eschental dienen.$b$bHauptmann Goggath in Höllschreis Wacht wird zweifellos hoch erfreut sein, den Kopf des erschlagenen Nachtsäblers entgegenzunehmen.', `Objectives`='Bringt Schattumbras Kopf zu Hauptmann Goggath in Höllschreis Wacht.', `OfferRewardText`='Schattumbras Kopf?$B$BWer weiß, wie viele unserer Hordenbrüder dieser Bestie über die Jahre zum Opfer gefallen sind? Eure Tapferkeit hat sichergestellt, dass niemand mehr diesem Schicksal erliegt.$B$BKriegshäuptling Höllschrei soll von Euren Taten hören, $C.', `RequestItemsText`='Ja, $C?' WHERE  `entry`=24 LIMIT 1;
-- Übersetze Und dann langsam abkühlen lassen
UPDATE `quest_template` SET `Title`='Und dann langsam abkühlen lassen', `Details`='Das hättet Ihr sehen sollen, $c!Die Elfen dachten, Silberwind wäre uneinnehmbar. Bei all ihren vielen Verteidigungsmaßnahmen und ihrer Armee von Wasserelementaren hat das auch beinahe gestimmt.$b$bBeinahe.$b$bEinem unserer Magier ist es gelungen, einen verdorbenen Elementar zu beschwören, der die anderen in wilde Raserei versetzen sollte.$b$bAhh, Ihr hättet nur deren Gesichter sehen sollen!$b$b<Tarkan lacht.>$b$bLeider ist der Magier, der die Beschwörung durchgeführt hat, im Kampf gefallen. Jetzt benötige ich jemanden, der die Misere in Ordnung bringt.', `Objectives`='Hauptmann Tarkan in der Silberwindzuflucht möchte, dass Ihr Tideress, sowie 12 beschmutzte Wasserelementare am Mystralsee erledigt.', `OfferRewardText`='Gut gemacht, $C.$B$BEin passendes Ende für einen vorbildlichen Angriff.' WHERE  `entry`=25 LIMIT 1;
-- Übersetze einen Teil von der Quest Weitere Sorgen
UPDATE `quest_template` SET `Title`='Weitere Sorgen', `Details`='Falls Ihr befürchtet, dass die Gerüchte über das Auftauchen von Murlocs wahr sein könnten, dann tut das Folgende: Begebt Euch zur östlichen Brücke von Elwynn und sprecht mit Wache Thomas. Er ist seit einer Woche an der Brücke stationiert und wird deswegen wissen, wie es in der Gegend aussieht.$B$BIch habe hier ein Streitross aus Sturmwind, das Euch zur Wache Thomas tragen wird. Lasst es mich wissen, wenn Ihr das Pferd benutzen wollt.', `Objectives`='Marschall Dughan möchte, dass Ihr mit Wache Thomas sprecht.' WHERE  `entry`=35 LIMIT 1;
-- Übersetze einen Teil von der Quest Suche nach den vermissten Wachen
UPDATE `quest_template` SET `Title`='Suche nach den vermissten Wachen', `Details`='Vor ein paar Tagen haben wir zwei Wachen, Rolf und Malakai, losgeschickt, damit sie entlang des Flusses Nachforschungen anstellen, aber bisher sind sie noch nicht zurückgekehrt. Damit ich meinen Bericht fertig schreiben kann, muss ich wissen, was den beiden Männern zugestoßen ist.$B$BSucht den Fluss in Richtung Norden ab und seht zu, dass Ihr die Wachen findet... oder ihre Überreste.', `Objectives`='Wache Thomas möchte, dass Ihr den Fluss in Richtung Norden nach Rolf und Malakai, den beiden vermissten Wachen, absucht.' WHERE  `entry`=37 LIMIT 1;